# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2923ed7cc045eb7c3c40c006a3809db83955222eb2ae04401de61a6566699832068e5a03f3fd4440417afba69556228ee2756d3432ae0465a2fe1628942203fe

test:
  secret_key_base: a27fd108b1bf98ab8910f592e3de8d9bde92d41c403c433b0b83ad091ef9d2458cc2c778cc14a0360a7e46323ef19664fa81f88373b8a744ed776bb6395d1272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
